title:   Mudit Singh
logo: "/images/WhatsApp%20Image%202023-12-28%20at%208.32.19%20PM.jpeg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br><br>
  Results-driven data analyst, product owner and business system analyst with experiences and a track record of delivering innovative technical solutions that enhance the experience of both customers and analytic professionals. Proficient in SQL, Python, and Power BI, with a validated competence to automate dashboards, streamline processes, and provide tactical direction to stakeholders using easy-to-understand language. Skilled in analyzing behavioral data, identifying business gaps, and developing solutions that meet the needs of both internal and external stakeholders.
  <br><br><br>
  <a href="https://www.linkedin.com/in/mudit-singh-68850a78/">View My LinkedIn Profile</a>
  <br><br><br>
  <a href="https://public.tableau.com/app/profile/mudit.singh2189/vizzes">View My Tableau Work Samples</a>
  <br><br><br>
  <a href="https://www.notion.so/muditsingh/Portfolio-d7855c23221d4cafa1d6e085f7cfffa7">View My Notion Portfolios</a>
  
theme: jekyll-theme-minimal   
 
